### ISSUE TITLE
Get-TfsWorkItemLink  - is/will this be how to access links?

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#119]
$workItem=Get-TfsWorkItem -WorkItem 2848 -Project $proj -Collection $coll

this works, but $workitem.Links.Links shows things that are not relevant.

Get-TfsWorkItemLink  - this doesn't appear to work at this point. But will this be how to retrieve links to other/external items?

**Comment by igoravl** [comment]
When using Get-TfsWorkItem, you will have the option to use the `-IncludeLinks` switch to fill the `Relations` property with all links in a work item. And Get-TfsWorkItemLink will yield the same results - in other words, either will work.

PR #121 incorporates the implementation for both. Stay tuned for the next release.

**Comment by igoravl** [comment]
Please refer to https://github.com/igoravl/TfsCmdlets/releases/tag/v2.0.0-rc.3%2B2310.2
