### ISSUE TITLE
How do I access attachments/count/names?

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#120]
$workItem=Get-TfsWorkItem -WorkItem 2848 -Project $proj -Collection $coll

I see the workitem. But I don't see how to retrieve any info about the attachments?

**Comment by igoravl** [comment]
You can list attachments by getting all links and filtering by the `Rel` property, as in the example below:

```powershell
Get-TfsWorkItem -WorkItem 2848 -Project $proj -Collection $coll | Get-TfsWorkItemLink | Where Rel -eq 'AttachedFile'
```

And to download the attachment contents, you can use the `Export-TfsWorkItemAttachment` cmdlet.

PR #121 incorporates the implementation for that. Stay tuned for the next release.

**Comment by igoravl** [comment]
Please refer to https://github.com/igoravl/TfsCmdlets/releases/tag/v2.0.0-rc.3%2B2310.2
