### ISSUE TITLE
Export-TfsWorkItemAttachment - 'No filter arguments have been specified'

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#154]
Export-TfsWorkItemAttachment -Destination "$DestFolder" -Force -WorkItem $CSO.id -Attachment "$PDF" -Collection $coll 
Export-TfsWorkItemAttachment : No filter arguments have been specified. Unable to perform a simple query.
At line:1 char:1
+ Export-TfsWorkItemAttachment -Destination "$DestFolder" -Force -WorkI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-TfsWorkItemAttachment], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,TfsCmdlets.Cmdlets.WorkItem.Linking.ExportWorkItemAttachment

Export-TfsWorkItemAttachment -Destination "$DestFolder" -Force -WorkItem $CSO.id -Attachment "$PDF" -Collection $coll -verbose
VERBOSE: [14:25:28.7200] [Export-TfsWorkItemAttachment] Running cmdlet with parameter set '__AllParameterSets' and the following arguments:
Export-TfsWorkItemAttachment : Self referencing loop detected with type 'Microsoft.TeamFoundation.Framework.Client.CatalogNode'. Path 
'Collection.CatalogNode.Resource.NodeReferences'.
At line:1 char:1
+ Export-TfsWorkItemAttachment -Destination "$DestFolder" -Force -WorkI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-TfsWorkItemAttachment], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,TfsCmdlets.Cmdlets.WorkItem.Linking.ExportWorkItemAttachment
 

NOTE: This works if I specify the work-item OBJECT, but fails when I try to use the $Item.ID
HELP says:
-WorkItem <object>
        Specifies a work item. Valid values are the work item ID or an instance of Microsoft.TeamFoundation.WorkItemTracking.WebApi.Models.WorkItem.

**Comment by igoravl** [comment]
Can you please check the type of the property $CSO.Id? I can reproduce your error when Id is not an Int32, as in such cases the cmdlet doesn't know how to properly parse it.

One way to work around the issue (assuming that's the case) would be to force a cast, such as in:

```powershell
Export-TfsWorkItemAttachment -Destination "$DestFolder" -Force -WorkItem ([int] $CSO.id) -Attachment "$PDF" -Collection $coll
```

**Comment by lukeb1961** [comment]
right. For some reason it's a string.
$TGTs = $CSOs.where({$_.Relations.LinkType -eq 'Attachment'})
$CSO = $TGTs[33]
$CSO.Id 
2521
$CSO.Id.gettype().fullname
System.String

**Comment by igoravl** [comment]
Thanks for confirming, @lukeb1961. I assume that unblocked you.

Although that's a rather edgy case, I'm adding logic to Get-TfsWorkItem so that IDs passed as strings get properly parsed and recognized.

It's coming in the next release. In the meantime, please keep insuring your IDs are passed as ints.

Please keep the feedback coming!
