### ISSUE TITLE
Get-TfsWorkItem : Error invoking async operation (VS403474: You requested 279 work items which exceeds the limit of 200. )

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#164]
This used to work. Recently I installed a new Win11 and the latest tfscmdlets.

Ran existing script and 
$CSOs = Get-TfsWorkItem -Collection $coll -Project $proj -WorkItemType 'Repair Items' -IncludeLinks

this line now fails.  Is there a way to have it get all 279 items?

**Comment by igoravl** [comment]
@lukeb1961 that was a known issue in versions 2.2.0 and 2.2.1. Next release (2.3.0) fixes it.

2.3.0 is likely to be released today or tomorrow.

**Comment by igoravl** [comment]
2.3.0 is released. Closing this issue. 

As always, thanks for the feedback!
