### ISSUE TITLE
Get-TfsWorkItem not returning workitem object ID correctly

### ISSUE THREAD

**Issue by lukeb1961** [igoravl/TfsCmdlets#172]
(get-module -name tfscmdlets).Version
2.3.1

$ItemId=3315
$workItem=Get-TfsWorkItem -IncludeLinks -Collection $coll -Where "[System.Id] = '$ItemId'"   
$workitem.Id 
3
$workitem.fields.'System.Id'
3315

This used to work, in earlier versions.

NOTE the explicit request works.
$workitem2=Get-TfsWorkItem -IncludeLinks -Collection $coll  -WorkItem 3315
$workitem2.Id
3315

**Comment by igoravl** [comment]
Thanks for the report. Due to a change in the underlying REST API the cmdlet stopped working as before. Fixed in 2.3.2.
