### ISSUE TITLE
Set-TfsWorkItem fails with {type} to {type}[] (array) conversion error

### ISSUE THREAD

**Issue by sztaylorakgov** [igoravl/TfsCmdlets#174]
### A quick summary and/or background

Use Set-TfsWorkItem to update Tags on a single work-item (also repro'd with Title)

### Steps to reproduce

1. Connect-TfsTeamProjectCollection
2. Connect-TfsTeamProject
3. Create and populate a string array with tag values
4. Create a string title value
5. Call Set-TfsWorkItem [id] -Tags {tag-vals}
6. Call Set-TfsWorkItem [id] -Title {title-val}

```
Get-Module TfsCmdlets:

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.4.0                 TfsCmdlets                          {Add-TfsGroupMember, Add-TfsTeamAdmin, Add-TfsTeamMember… 
```

$PSVersionTable:

```
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Give sample code if you can.

```
Connect-TfsTeamProjectCollection "{azure devops org name}" -PersonalAccessToken $SourcePAT

$TeamProject = "{team project name}"
Connect-TfsTeamProject $TeamProject

[string[]] $Tags = $null

$Tags += "foo:bar"
$Tags += "arp:blop"
$Tags

[string]$Title = ""
$Title = "Cool title, Hansel..."
$Title

Set-TfsWorkItem 2618 -Tags $Tags
Set-TfsWorkItem 2618 -Title $Title
```

### What you expected would happen

- Tags update
- Title updates

### What actually happens

```
Set-TfsWorkItem: C:\Users\xxxx\repos\TfsCmdletEx\Examples\exSet-TfsWorkItem-Tags.ps1:19:1
Line |
  19 |  Set-TfsWorkItem 2618 -Tags $Tags
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to cast object of type 'System.Int32' to type 'System.Int32[]'.

Set-TfsWorkItem: C:\Users\xxxx\repos\TfsCmdletEx\Examples\exSet-TfsWorkItem-Tags.ps1:20:1
Line |
  20 |  Set-TfsWorkItem 2618 -Title $Title
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to cast object of type 'System.String' to type 'System.String[]'.
```

### Notes (possibly including why you think this might be happening, or stuff you tried that didn't work)

I took the same approach that works to set -Tags in New-TfsWorkItem; i.e., create a string array of the values.  I also tried just using a string instead of a string array, which didn't work either.  

It's interesting that for both the attempt to set the Tags and the Title the error is a conversion error from a {type} to {type}[].

**Comment by igoravl** [comment]
Hey @sztaylorakgov , would you please take a look at the newest release (2.4.1) and see whether it solved your issue?

Thanks!

**Comment by sztaylorakgov** [comment]
Hi, @igoravl.  Tested with 2.4.1.  Worked perfectly.  Thanks for the fix!
