### ISSUE TITLE
UpdateRepositoryEnabledStatus not working

### ISSUE THREAD

**Issue by MarioMajcicaAtABNAMRO** [igoravl/TfsCmdlets#221]
If I do execute the above mentioned cmdlet I do get back a response saying "The required anti-forgery cookie &quot;__RequestVerificationToken&quot; is not present."
Any idea if we can or how to set repo settings without that token? I'm sure the REST API is not exposing an endpoint to do this, but I was hoping in a working undocumented endpoint.

**Comment by MarioMajcicaAtABNAMRO** [comment]
Sorry, wrong cmdlet

**Comment by igoravl** [comment]
Thanks for the report. I'll take a look at it ASAP. My guess is that some
change in the service side may have broken my hack.

Can you confirm whether you're using Azure DevOps Services or Server? If
Server, what version?


Em qua., 26 de jun. de 2024, 17:44, Mario Majcica @ AAB <
***@***.***> escreveu:

**Comment by MarioMajcicaAtABNAMRO** [comment]
Sorry it is working as expected, it was an issue on my side.

**Comment by igoravl** [comment]
Thanks for the follow-up!

Em qua., 26 de jun. de 2024, 17:51, Mario Majcica @ AAB <
***@***.***> escreveu:
