### ISSUE TITLE
The installer created a non intuitive folder and shortcut

### ISSUE THREAD

**Issue by egomesbrandao** [igoravl/tfscmdlets#3]
The installer has created a shortcut folder and intuitive , like the image below , I think the shortcut name must be TfsCmdLets

![2015-09-09 12_18_47-greenshot](https://cloud.githubusercontent.com/assets/62425/9765976/263da35a-56ed-11e5-91cc-b7277378c363.png)

**Comment by igoravl** [comment]
@egomesbrandao TfsCmdlets is the name of the PowerShell module. As such, it can be loaded and used in any PS console - all it takes is a _Import-Module TfsCmdlets_ (in fact, in PowerShell v3+ it usually isn't necessary).

On the other hand, the MSI-provided shortcut ("Team Foundation Server Shell") is a custom PS shell that, among other things, provide a custom prompt and preloads the TfsCmdlets module. In the future it can be do more than that - for example, preload other TFS-related tools (such as the TFS Power Tools PS snapin) and setting the VS environment vars. Thus notice that it is not limited to TfsCmdlets, but should be seen instead as a general-purpose TFS admin shell, hence the name.

Makes sense?

**Comment by egomesbrandao** [comment]
Yes, make sense...
