### ISSUE TITLE
Support for TFS work item links

### ISSUE THREAD

**Issue by jessehouwing** [igoravl/TfsCmdlets#43]
Parent-Child relationships would be possible using the Powershell containers, which would allow Move and Create-Item, Get-ChildItem, Get-Parent etc.

Other links probably using the "Add-WorkItemLink" and "Remove-WorkItemLink".

**Comment by jessehouwing** [comment]
Alternative could be 

"Connect-Workitems" and "Disconnect-WorkItems" from the list of approved communication verbs,

**Comment by igoravl** [comment]
Add-WorkItemLink is supported for quite some time now. Deferring the implementation of remaining CRUD cmdlets to a future release.
