### ISSUE TITLE
Add the ablitity to create a Team Administrator

### ISSUE THREAD

**Issue by nschonni** [igoravl/TfsCmdlets#57]
Haven't seen a real API for this, and I'd be interested in your take :wink:

**Comment by igoravl** [comment]
Challenge accepted! :-)

Jokes aside, I don't know how to do it, but I agree it'd be a useful addition. I'll take a look at it.

**Comment by igoravl** [comment]
This one also took a "bit" longer than I expected :-), but hopefully it's not "too little too late". PR #85 just fixed that. You might want to take a look at today's release.
