### ISSUE TITLE
Connect-TfsTeamProjectCollection additional prompt when authenticating to VSTS (VSO)

### ISSUE THREAD

**Issue by seanloosier** [igoravl/tfscmdlets#65]
Hello, I'm attempting to connect to Visual Studio Team Services (formerly Visual Studio Online) with the following command and Alternate Credentials:

Connect-TfsTeamProjectCollection -Collection "https://<org-name>.visualstudio.com/DefaultCollection" -Credential $myCred

It prompts me for my username and password (the normal windows dialog) which I enter correctly, then it prompts again (this time using single sign-on UI). The goal is to supply a PS-Credential object which should take care of the first windows credential prompt, however I need to not be prompted a second time. Am I doing something wrong here or is this a bug?

Thanks for any inputs
-sean

**Comment by igoravl** [comment]
Sean, I agree that the experience when connecting to VSTS is less than ideal right. There's a fix in the works for the next release.

In the mean time, can you please try using either Alternate Credentials ou Personal Access Tokens when logging in to VSTS? This way, you can provide your alt creds to the Windows login dialog in order to log in to VSTS.

HTH,
   Igor

**Comment by seanloosier** [comment]
Hello Igor, Thanks for getting back to me. The situation with the two dialog boxes happens to me while using the Alternate Credentials. I can get it down to just the SSO login UI if I do something like the following:

Get-Credential $myCred
[enter alternate credential in the windows login dialog]
Connect-TfsTeamProjectCollection -Collection "https://*org_name*.visualstudio.com/DefaultCollection" -Credential $myCred

I can't seem to figure out how to get both of the login prompts to go away. 

I have enabled a Personal Access Token, how would I use it with a powershell credential object? would I just leave the username blank?

Thanks again for getting back to me!

**Comment by igoravl** [comment]
Fixed in version merged to `master`. Fix is going to be released in 1.0.0-alpha9.

**Comment by seanloosier** [comment]
Very good! Thank you very much! I won't be able to test it until after the
new year but I will test it and let you know how it works!

Thanks again!
-sean

**Comment by seanloosier** [comment]
I was able to install  1.0.0-alpha9 with chocolatey I had a couple of issues along the way though

1) I wasn't able to install  1.0.0-alpha9 clean, I had to install  1.0.0-alpha7 and then upgrade to  1.0.0-alpha9. I'm not sure if this is user error or not. I can try it again if you need me too. 

2) using the same command as above I'm now getting a different error:

`Error connecting to team project collection https://redlobster.visualstudio.com/DefaultCollection (Could not load file
or assembly 'Microsoft.VisualStudio.Services.Common, Version=14.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.)
At C:\ProgramData\chocolatey\lib\TfsCmdlets\Tools\Tfscmdlets\Connection\Connection.psm1:191 char:4
+             throw "Error connecting to team project collection $Collection ($_)"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error connectin...ile specified.):String) [], RuntimeException
    + FullyQualifiedErrorId : Error connecting to team project collection https://redlobster.visualstudio.com/DefaultC
   ollection (Could not load file or assembly 'Microsoft.VisualStudio.Services.Common, Version=14.0.0.0, Culture=neut
  ral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.)`
