### ISSUE TITLE
Add support for -Whatif for cmdlets that change state

### ISSUE THREAD

**Issue by dtewinkel** [igoravl/tfscmdlets#66]
As a script developer, I would like to see support for -WhatIf for cmdlets that change state in TFS / VSTS, so that I can better test the scripts before I execute them.

**Comment by igoravl** [comment]
All state-changing (Import, Mount, Move, New, Rename, Set, Start) and destructive (Dismount, Remove, Stop) cmdlets in TfsCmdlets will have *SupportsShouldProcess* support in the next release.
