### ISSUE TITLE
Create Link-Iteration Cmdlet

### ISSUE THREAD

**Issue by elipsion** [igoravl/TfsCmdlets#72]
Arguments:
TfsIteration
TfsTeam

**Comment by igoravl** [comment]
@elipsion maybe a bit too late, but would you care to elaborate?

**Comment by elipsion** [comment]
I **think** that I was trying to create nested _Iterations_  in bulk, but couldn't find a way of doing it.

**Comment by igoravl** [comment]
FWIW, you can do that by passing the full path in the call to New-TfsIteration. Given the following call:

```
New-TfsIteration -Iteration 'Iteration1\Iteration2\Iteration3\Iteration4'
```

If any of the iterations (Iteration1, Iteration1\Iteration2, Iteration1\Iteration2\Iteration3 or Iteration1\Iteration2\Iteration3\Iteration4) doesn't exist, it's created automatically.

It *should* work in the v1 branch, but I can't tell for sure now. Nevertheless, v2 does support it (I just tested it).
