### ISSUE TITLE
Credentials for unattended use

### ISSUE THREAD

**Issue by caderoux** [igoravl/TfsCmdlets#76]
I wanted to script some extractions and reports to Excel which combine results from different TFS projects, and these cmdlets work great.  However, I am trying to script them unattended, and am having difficulty getting authentication working on the TFS components.

Similar operations to make credentials for SMTP are working fine in my script:

```
$TFSsecstr = New-Object -TypeName System.Security.SecureString
$TFSPassword.ToCharArray() | ForEach-Object {$TFSsecstr.AppendChar($_)}

# This is what we use for making SMTP
$TFScred = new-object -typename System.Management.Automation.PSCredential -argumentlist $TFSAccount, $TFSsecstr

# I've also tried this one which is internal to the TFS cmdlets
# $TFScred = Get-TfsCredential -UserName $TFSAccount -Password $TFSsecstr

# Passing the credentials here never works, but using the interactive prompt will
Connect-TfsTeamProjectCollection $Collection # -Credential $TFScred
```

**Comment by igoravl** [comment]
Added on v2.0. Use the Get-TfsCredential cmdlet to build credentials for unattended use and pass them to the -Credential argument.
