### ISSUE TITLE
Question : supports of MacOS installation version with .NET Core?

### ISSUE THREAD

**Issue by rashelinu** [igoravl/TfsCmdlets#77]
Is this module is intended to be executed on a MacOS with the .NET Core and Powershell installed? My computer is a Mac, and when I try it, I can install it with Nuget.exe and start the command let. But I have an error that it doesn't find the System.Windows.Form namespace, which is not available for the MacOS. 

Because the CmdLet is a command line and Powershell application, ant that it call Visual Studio, is there a way to remove the System.Windows.Form to compile a MacOS compatible version?

**Comment by igoravl** [comment]
Unfortunately it's not currently possible. TfsCmdlets rely on the old TFS Client Object Model, which in turn is Windows only.

I'm tinkering with the idea of porting TfsCmdlets to PSCore, dropping the TFS ClientOM and replacing it with the new TFS REST API in the process. But I think we're still a few months away from it.

By the way, given that there would necessarily be a compatibility break (the underlying objects would be different), what would you expect from a xplat, PSCore-based version of TfsCmdlets? What is (or isn't) acceptable?

**Comment by nschonni** [comment]
You might want to look at https://github.com/DarqueWarrior/vsteam since it's already built on the REST endpoints and runs on PSCore

**Comment by rashelinu** [comment]
Oh thank you so much I will check it out! :) :)

-- 
Rachel Lavoie

Le 22 janvier 2019 à 23:41:33, Nick Schonning (notifications@github.com) a
écrit:

**Comment by igoravl** [comment]
Closed by #103
